<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8" />
	<meta name="author" content="spert" />
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
	<meta name="description" content="SPERT S.A. de C.V." />
	<meta name="keywords" content="" />
	<link rel="stylesheet" href="estilo/normalize.css" />
	<link rel="stylesheet" href="estilo/estilos.css" />
	<link rel="stylesheet" href="fonts/fonts.css" />
	<link href='http://fonts.googleapis.com/css?family=Arimo:400,700,400italic' rel='stylesheet' type='text/css'>
	<link rel="icon" type="image/x-icon" href="./images/fav.ico" />
	<!--[if lt IE 9]><script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script><![endif]-->
	<title><?= $titulo ?></title>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/> 
</head>
<body>
	<header>
		<div class="menu_bar">
			<a href="#" class="bt-menu"><img src="images/logo.png" alt="SPERT"><span class="icon-menu"></span></a>
		</div>
		<nav>
			<div class="social">
				<ul>
					<li><a href="aviso"><u>Aviso de P</u></a></li>
					<li><a href="#"><span class="icon-twitter4"></span></a></li>
					<li><a href="https://www.facebook.com/spertish" target="_blank"><span class="icon-facebook3"></span></a></li>
					<li><a href="#"><span class="icon-linkedin2"></span></a></li>
				</ul>
			</div>
			<ul>
				<li class="logo"><a href="/america"><img src="images/logo.png" alt="SPERT"></a></li>
				<li class="home"><a href="/america">Inicio</a></li>
				<li class="submenu"><a href="nosotros">¿Quienes somos? <span class="icon-arrow-down4"></span></a>
					<ul class="children childuno">
						<li><a href="#"><span class="icon-arrow-right3"></span>Misión | Visión</a></li>
						<li><a href="#"><span class="icon-arrow-right3"></span>Nuestros Clientes</a></li>
					</ul>
				</li>
				<li class="submenu">
					<a href="servicios">Áreas de Negocio <span class="icon-arrow-down4"></span></a>
					<ul class="children">
						<li><a href="#"><span class="icon-arrow-right3"></span>Procesos</a></li>
						<li><a href="#"><span class="icon-arrow-right3"></span>Continuidad de Negocio</a></li>
						<li><a href="#"><span class="icon-arrow-right3"></span>Sistema de Gestión de Calidad</a></li>
						<li><a href="#"><span class="icon-arrow-right3"></span>Reclutamiento y Selección de Personal</a></li>
					</ul>
				</li>
				<li><a href="">Casos de Éxito</a></li>
				<li class="submenu"><a href="#">Divisiones de Negocio <span class="icon-arrow-down4"></span></a>
					<ul class="children childuno">
						<li><a href="http://spazzio.spert.com.mx" target="_blank"><span class="icon-arrow-right3"></span>SPAZZIO</a></li>
						<li><a href="#"><span class="icon-arrow-right3"></span>JJandB</a></li>
					</ul>
				</li>
				<li><a href="http://post.spert.com.mx">Artículos</a></li>
				<li><a href="contacto"></span>Contacto</a></li>
				<li class="menu_aviso"><a href="aviso">Aviso de Privacidad</a></li>
			</ul>
		</nav>
	</header>	
	<section>